fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppetlabs_apt: "git://github.com/puppetlabs-operations/puppet-puppetlabs_apt.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
  symlinks:
    puppet: "#{source_dir}"
