name          'gdsoperations-puppet'
version       '0.0.2'
source        'https://github.com/alphagov/puppet-puppet'
author        'Government Digital Service'
license       'MIT'
summary       'Puppet module for managing Puppet'
description   'Puppet module for managing Puppet'
project_page  'https://github.com/alphagov/puppet-puppet'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'ploperations/puppetlabs_apt', '>= 0'
